from os import getenv

MAX_COURSES_TO_SEND = int(getenv("MAX_COURSES_TO_SEND"))
PAGES_TO_SCRAPE = int(getenv("PAGES_TO_SCRAPE"))
CHROMEDRIVER_PATH = getenv("CHROMEDRIVER_PATH")
GOOGLE_CHROME_BIN = getenv("GOOGLE_CHROME_BIN")
PAGE_LOAD_TIME = getenv("PAGE_LOAD_TIME")
PAGE_LOAD_TIME = None if PAGE_LOAD_TIME is None else int(PAGE_LOAD_TIME)

FREE_COURSE_DISCOUNT = 100
