from os import getenv

PAGES_TO_SCRAPE = getenv("PAGES_TO_SCRAPE")
PAGES_TO_SCRAPE = None if PAGES_TO_SCRAPE is None else int(PAGES_TO_SCRAPE)
CHROMEDRIVER_PATH = getenv("CHROMEDRIVER_PATH")
GOOGLE_CHROME_BIN = getenv("GOOGLE_CHROME_BIN")
PAGE_LOAD_TIME = getenv("PAGE_LOAD_TIME")
PAGE_LOAD_TIME = None if PAGE_LOAD_TIME is None else int(PAGE_LOAD_TIME)

FREE_COURSE_DISCOUNT = 100
